
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jpa:
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
    sql:
      init:
        data-locations: "classpath*:/data.sql"
        mode: always
    h2:
      console:
        enabled: true
        path: /h2-console
        settings.trace: false
        settings.web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  pattern:
    console: "%white([%d{yyyy-MM-dd HH:mm:ss}]) %yellow([%thread]) %highlight([%-5level]) %white([%-35logger{35}]) %white(%msg  %n)"
  level:
    root: INFO
    jpa: debug
    org:
      springframework:
        orm:
          jpa: INFO

oauth:
  kakao:
    client_id: 601960133f76e1c25529d3fd224a24be
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: js6VznxiZLWBftAlVvEgesrxDVsgmlXO
    scope: profile_nickname, profile_image
